# Generated by Django 2.2.19 on 2021-12-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20, verbose_name='単語')),
                ('pos_tag', models.CharField(max_length=20, verbose_name='品詞')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese_question', models.CharField(max_length=50, verbose_name='日本語問題文')),
                ('english_question', models.CharField(max_length=50, verbose_name='英語問題文')),
            ],
        ),
    ]
